#!/bin/sh

set -ex

echo "configuring Dynatrace CLI with $apitoken and $tenanthost"

python /dtcli/dtcli.py config apitoken $apitoken tenanthost $tenanthost debug 1

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export CURRENT_APP_COLOR=$(cat ./current-app-info/current-app.txt)

eval monspeccomparison=$monspeccomparison

echo "Validating load test results via monspec comparison $monspeccomparison"
#echo "Current seconds since epoch is $(date -u +%s)"

# fetching monspec comparison results, pretty-printing them, then failing if totalViolations > 0 via POSIX compliant logic for portability

python /dtcli/dtcli.py monspec pullcompare ./music-repo/ci/smplmonspec.json ./music-repo/ci/smplpipelineinfo.json $monspeccomparison 5 > monspecpullcompare.json
jq '.' monspecpullcompare.json
totalViolations="$(jq -r '.totalViolations' monspecpullcompare.json)"
echo $totalViolations
if [ $totalViolations -gt 0 ]; then
echo "We encountered $totalViolations monspec violations, failing build"
exit 1
else 
echo "No monspec violations encountered"
exit 0
fi

